### ISSUE TITLE
Add info to datapackage

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/lab1-dfa#24]
See [documentation here](https://specs.frictionlessdata.io/data-package/#contributors).

See an example here:
```yaml

profile: data-package
resources:
  - name: data2
    path: >-
      https://raw.githubusercontent.com/dennisangemi/lab1-dfa/main/exp-4/data/experimental-data-2.csv
    profile: tabular-data-resource
    schema:
      fields:
        - name: event
          type: integer
          format: default
        - name: distance
          type: string
          format: default
        - name: time
          type: integer
          format: default
        - name: uncertainty
          type: integer
          format: default
        - name: uom
          type: string
          format: default
name: experiment-4
title: Experiment 4 pendulum bla bla - Physics laboratory 1 lorem ipsum dolor sit amet bla bla
description: Compound pendulum lorem ipsum dolor sit amet bla
contributors:
  - title: Dennis Angemi
    email: dennisangemi@gmail.com
    role: author
  - title: Federica Ingrassia
    email: fedeingrassia@outlook.com
  - title: Giuseppe Di Silvestre
    email: giuseppedisilv@gmail.com
  - title: Giulia De Luca
    email: giulia.deluca14@virgilio.it
licenses:
  - name: CC-BY-4.0
    title: Creative Commons Attribution 4.0
    path: https://creativecommons.org/licenses/by/4.0/

```

Add Title, description, contributors 

- [x] exp-1
- [x] exp-2
- [x] exp-3
- [x] exp-4
- [ ] exp-5
